src/debian_reimbursements/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("reports/", include("reports.urls")),
    path("requests/", include("reimbursements.urls")),
    path("", include("webui.urls")),
]

src/webui/urls.py
from django.urls import path

from webui.views import DeleteBankDetailsView, IndexView, ProfileEditView, ProfileView

urlpatterns = [
    path("", IndexView.as_view()),
    path("profile", ProfileView.as_view(), name="profile"),
    path("profile/edit", ProfileEditView.as_view(), name="profile-edit"),
    path(
        "profile/delete-bank-details",
        DeleteBankDetailsView.as_view(),
        name="profile-delete-bank-details",
    ),
]

src/reimbursements/models/profile.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Profile(models.Model):
    bank_details = models.JSONField(blank=True)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"Profile for {self.user}"

src/reimbursements/models/request.py
from datetime import timedelta
from decimal import Decimal

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.core.files import File
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils import crypto, timezone

from image_wrangler.client import PDFBundlerClient
from reimbursements.storage import generate_bundle_filename, receipts_storage

from reimbursements.models.history import RequestHistory
from reimbursements.models.reimbursement import ReimbursementLine
from reimbursements.models.types import RequestType, ExpenseTypeAllocation

User = get_user_model()


class Request(models.Model):
    class States(models.TextChoices):
        DRAFT = "draft", _("Draft")
        PENDING_APPROVAL = "pending_approval", _("Pending Approval")
        APPROVED = "approved", _("Approved")
        DELETED = "deleted", _("Deleted")
        PENDING_PAYMENT = "pending_payment", _("Pending Payment")
        PAID = "paid", _("Paid")

    requester = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    parent = models.ForeignKey(
        "Request",
        on_delete=models.PROTECT,
        null=True,
        related_name="children",
        blank=True,
    )
    state = models.CharField(
        max_length=16, choices=States.choices, default=States.DRAFT
    )
    bank_details = models.JSONField(null=True, blank=True)
    request_type = models.ForeignKey(RequestType, on_delete=models.PROTECT)
    description = models.TextField()
    expected_date = models.DateField(null=True, blank=True)
    currency = models.CharField(max_length=3, default=settings.DEFAULT_CURRENCY)
    approver_group = models.ForeignKey(
        Group, on_delete=models.PROTECT, null=True, related_name="requests_approver"
    )
    payer_group = models.ForeignKey(
        Group, on_delete=models.PROTECT, related_name="requests_payer"
    )
    visible = models.BooleanField(default=False)

    @property
    def subject(self):
        lines = self.description.splitlines()
        if lines:
            return lines[0].strip()
        return ""

    @property
    def total(self):
        return (
            self.lines.aggregate(total=models.Sum("amount"))["total"] or Decimal(0),
            self.currency,
        )

    @property
    def receipts_total(self):
        from reimbursements.models.receiptline import ReceiptLine

        lines = ReceiptLine.objects.filter(receipt__request=self)
        return (
            lines.aggregate(total=models.Sum("converted_amount"))["total"]
            or Decimal(0),
            self.currency,
        )

    @property
    def reimbursed_total(self):
        lines = ReimbursementLine.objects.filter(request=self)
        return (
            lines.aggregate(total=models.Sum("amount"))["total"] or Decimal(0),
            self.currency,
        )

    @property
    def created(self):
        try:
            return self.history.get(event=RequestHistory.Events.CREATED).timestamp
        except RequestHistory.DoesNotExist:
            return None

    @property
    def updated(self):
        last_event = self.history.all().last()
        if last_event:
            return last_event.timestamp
        return None

    def get_absolute_url(self):
        return reverse("request", kwargs={"pk": self.pk})

    def get_fully_qualified_url(self):
        return settings.SITE_URL.rstrip("/") + self.get_absolute_url()

    def summarize_by_type(self):
        summary = {}
        total = ExpenseTypeAllocation("Total", self.currency, special=True)
        for line in self.lines.all():
            if line.expense_type_id not in summary:
                summary[line.expense_type_id] = ExpenseTypeAllocation(
                    line.expense_type.name, self.currency
                )
            summary[line.expense_type_id].requested += line.amount
            total.requested += line.amount
        for line in self.reimbursement_lines.all():
            if line.expense_type_id not in summary:
                summary[line.expense_type_id] = ExpenseTypeAllocation(
                    line.expense_type.name, self.currency
                )
            summary[line.expense_type_id].reimbursed += line.amount
            total.reimbursed += line.amount
        for receipt in self.receipts.all():
            for line in receipt.lines.all():
                if line.expense_type_id not in summary:
                    summary[line.expense_type_id] = ExpenseTypeAllocation(
                        line.expense_type.name, self.currency
                    )
                summary[line.expense_type_id].spent += line.converted_amount
                total.spent += line.converted_amount
        summary["total"] = total
        return summary

    def summarize_by_type_dict(self):
        allocation = {}
        for k, v in self.summarize_by_type().items():
            allocation[v.name] = v.to_dict()
        return allocation

    @property
    def approved_budget_limit(self):
        """The total requested, plus acceptable leeway"""
        total = self.total[0]
        approved_limit = total * (
            1 + Decimal(settings.OVERBUDGET_LEEWAY_PERCENTAGE) / 100
        )
        return (approved_limit, self.currency)

    @property
    def total_reimburseable(self):
        """The total requested, cut off at approved_budget_limit"""
        approved_total = min(self.approved_budget_limit[0], self.receipts_total[0])
        return (approved_total, self.currency)

    @property
    def within_budget(self):
        budget = self.approved_budget_limit[0]
        receipts_total = self.receipts_total[0]
        return receipts_total <= budget

    @property
    def over_budget(self):
        return not self.within_budget

    def __str__(self):
        return f"Request {self.id}: {self.subject}"

    def user_access(self, user, access_key=False):
        """What access levels does user have to this Request"""
        access = {}
        if self.requester == user and self.requester is not None:
            access["requester"] = True
        if user.is_superuser:
            access["admin"] = True
        if self.visible:
            if user.groups.filter(id=self.approver_group_id).exists():
                access["approver"] = True
            if user.groups.filter(id=self.payer_group_id).exists():
                access["payer"] = True
        if access_key:
            access["access_key"] = True
        return access

    @property
    def requester_name(self) -> str | None:
        """Helper for templates, to render the requester's name"""
        if not self.requester:
            return "Currently Unclaimed"
        name = self.requester.get_full_name()
        if not name:
            name = self.requester.username
        return name

    def generate_pdf_bundle(self):
        """Create a PDF bundle of the request"""
        content = [
            {"url": self.get_fully_qualified_url()},
        ]
        files = []
        for receipt in self.receipts.all():
            content.append({"filename": receipt.file.name})
            files.append(receipt.file)
        manifest = {"content": content}
        PDFBundlerClient(manifest, self, files).bundle_pdf()

    @property
    def pdf_bundle(self) -> File:
        """Open the PDF bundle file and return it."""
        return receipts_storage.open(generate_bundle_filename(self))

    def delete_pdf_bundle(self):
        """Delete any existing PDF bundle."""
        return receipts_storage.delete(generate_bundle_filename(self))

    def initiate_transfer(self, expire_days=60):
        from reimbursements.models.transfer import RequestTransfer

        transfer = RequestTransfer(
            request=self,
            expires=timezone.now() + timedelta(days=expire_days),
            token=crypto.get_random_string(length=20),
        )
        transfer.save()
        return transfer

    @property
    def pretty_bank_details(self) -> dict[str, str] | None:
        from reimbursements.forms.bank_details import label_bank_details

        if self.bank_details:
            return label_bank_details(self.bank_details)
        return None

src/webui/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


class UserEditForm(forms.Form):
    username = forms.CharField(max_length=150, required=True)
    name = forms.CharField(max_length=300, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit("submit", _("Update")))

    def clean_username(self):
        username = self.cleaned_data["username"]
        if "username" in self.changed_data:
            User = get_user_model()
            if User.objects.filter(username=username).exists():
                raise ValidationError(
                    f"A user with username {username} already exists."
                )

        return username

src/webui/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import FormView

from reimbursements.forms.bank_details import label_bank_details
from reimbursements.models import Profile, Request
from webui.forms import UserEditForm

log = logging.getLogger(__name__)


class IndexView(TemplateView):
    template_name = "webui/index.html"


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "webui/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviewable = {}
        payable = {}
        for group in self.request.user.groups.all():
            requests = group.requests_approver.filter(
                state=Request.States.PENDING_APPROVAL
            )
            if requests.exists():
                reviewable[group.name] = requests.all()
            requests = group.requests_payer.filter(state=Request.States.PENDING_PAYMENT)
            if requests.exists():
                payable[group.name] = requests.all()
        context["reviewable"] = reviewable
        context["payable"] = payable
        return context


class ProfileEditView(LoginRequiredMixin, FormView):
    template_name = "webui/profile_edit.html"
    form_class = UserEditForm

    def get_initial(self):
        user = self.request.user
        return {
            "username": user.username,
            "name": user.get_full_name(),
        }

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        salsa_account = self.request.user.socialaccount_set.filter(provider="salsa")
        context["salsa_account"] = salsa_account.exists()
        if salsa_account.exists():
            salsa_account = salsa_account.first()
            context["salsa_uid"] = salsa_account.uid
            context["salsa_username"] = salsa_account.extra_data["username"]
            context["salsa_web_url"] = salsa_account.extra_data["web_url"]

        try:
            bank_details = self.request.user.profile.bank_details
        except Profile.DoesNotExist:
            context["bank_details"] = None
        else:
            context["bank_details"] = label_bank_details(bank_details)

        return context

    def form_valid(self, form):
        user = self.request.user
        for k, v in self.get_initial().items():
            if v != form.cleaned_data[k]:
                if k == "username":
                    log.info(
                        "User %s changed their username to %s", v, form.cleaned_data[k]
                    )

                if k == "name":
                    split = form.cleaned_data["name"].partition(" ")
                    user.first_name = split[0]
                    user.last_name = split[2]
                else:
                    setattr(user, k, form.cleaned_data[k])

        user.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("profile")


class DeleteBankDetailsView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            profile = request.user.profile
        except Profile.DoesNotExist:
            pass
        else:
            profile.bank_details = {}
            profile.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("profile-edit")

src/webui/templates/webui/index.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{{ SITE_NAME }}{% endblock %}
{% block content %}
<h1>{{ SITE_NAME }}</h1>
{% if SITE_PROD_STATE == "dev" %}
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">
      <i class="bi bi-exclamation-triangle-fill"></i>
      {% trans "Development System" %}
    </h4>
    <p>
      {% blocktrans %}
        This is an experimental, in-development system.
        It isn't being used for anything real.
        Don't believe anything it says, or expect data to be persistent.
      {% endblocktrans %}
    </p>
  </div>
{% elif SITE_PROD_STATE == "beta" %}
  <div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">
      <i class="bi bi-exclamation-triangle-fill"></i>
      {% trans "Development System" %}
    </h4>
    <p>
      {% blocktrans %}
        This is still an in-development system.
        It will replace the RT-based reimbursement flows.
      {% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}
        You may make requests using this system.
        Feel free to fall back to the RT-based flow if you run into problems.
      {% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}
        You may encounter bugs.
        Please file them <a
          href="https://salsa.debian.org/stefanor/debian-reimbursement/-/issues">here</a>.
      {% endblocktrans %}
    </p>
  </div>
{% endif %}
<h2>{% trans "The process" %}</h2>
<p>
  {% blocktrans %}
    This system lets you request approval for expenses, collect receipts, and
    receive reimbursement. The process is:
  {% endblocktrans %}
</p>
<ol>
  <li>
    {% url "request-new" as file_url %}
    {% blocktrans %}
      <a class="btn btn-primary" href="{{ file_url }}">File</a>
      File a pre-approval request.
    {% endblocktrans %}
  </li>
  <li>{% trans "Receive approval from the DPL." %}</li>
  <li>{% trans "Make the expenses, up to the approved amount." %}</li>
  <li>{% trans "Upload receipts for the expenses." %}</li>
  <li>{% trans "Submit the receipts and request reimbursement." %}</li>
  <li>{% trans "Receive reimbursement from a Debian TO." %}</li>
</ol>
{% endblock %}

src/webui/templates/webui/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block page_title %}{% trans 'Profile' %}{% endblock %}
{% block content %}
<h1>{% trans 'Profile' %}</h1>
<h2>{% trans 'My Requests' %}</h2>
<ul>
  {% for request in request.user.request_set.all %}
    <li>
      {% translate "View" as action %}
      {% include "webui/includes/request-list-item.html" with request=request action=action %}
    </li>
  {% empty %}
    <li>{% trans 'No previous requests' %}</li>
  {% endfor %}
</ul>
<a href="{% url "request-new" %}" class="btn btn-secondary">New Request</a>
{% if reviewable %}
  <h2>{% trans 'Reviewable Requests' %}</h2>
  {% for group, requests in reviewable.items %}
    <h3>
      {% blocktrans with group=group %}
        For {{ group }}
      {% endblocktrans %}
    </h3>
    <ul>
      {% for request in requests %}
        <li>
          {% translate "Review" as action %}
          {% include "webui/includes/request-list-item.html" with request=request %}
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endif %}
{% if payable %}
  <h2>{% trans 'Payable Requests' %}</h2>
  {% for group, requests in payable.items %}
    <h3>
      {% blocktrans with group=group %}
        For {{ group }}
      {% endblocktrans %}
    </h3>
    <ul>
      {% for request in requests %}
        <li>
          {% translate "Pay" as action %}
          {% include "webui/includes/request-list-item.html" with request=request %}
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endif %}
{% endblock %}

src/webui/templates/webui/profile_edit.html
{% extends 'base.html' %}
{% load allauth socialaccount %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block page_title %}{% trans 'Account Settings' %}{% endblock %}
{% block content %}
<h1>{% trans 'Account Settings' %}</h1>
{% crispy form %}
<p>
  <a href="{% url "account_change_password" %}" class="btn btn-warning">
    {% trans "Change Password" %}
  </a>
</p>
<p>
  <a href="{% url "account_email" %}" class="btn btn-warning">
    {% trans "Change Email" %}
  </a>
</p>
<p>
  {% if salsa_account %}
    {% blocktrans %}
      Connected to Salsa account <a href="{{ salsa_web_url }}">
        {{ salsa_username }} ({{ salsa_uid }})</a>.
    {% endblocktrans %}
    <a href="{% url "socialaccount_connections" %}" class="btn btn-warning">
      {% trans "Manage Connections" %}
    </a>
  {% else %}
    <a href="{% provider_login_url 'salsa' process='connect' %}" class="btn btn-warning">
      {% trans "Connect to Salsa" %}
    </a>
  {% endif %}
</p>
<h2>{% trans "Saved Bank Details:" %}</h2>
  {% if bank_details %}
    <table class="table table-striped">
      {% for k, v in bank_details.items %}
        <tr>
          <th>{{ k }}</th>
          <td>{{ v }}</td>
        </tr>
      {% endfor %}
    </table>
    <form method="post" action="{% url "profile-delete-bank-details" %}">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" name="delete" value="{% trans "Delete" %}">
    </form>
  {% else %}
    <p>{% trans "Not saved" %}</p>
  {% endif %}
{% endblock %}