src/debian_reimbursements/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("reports/", include("reports.urls")),
    path("requests/", include("reimbursements.urls")),
    path("", include("webui.urls")),
]

src/reimbursements/urls.py
from django.urls import path

from reimbursements.views.bank_details import (
    BankDetailsView,
    BankFormSelectorView,
)
from reimbursements.views.lifecycle import (
    RequestCommentView,
    RequestDeleteView,
    RequestReimburseReturnView,
    RequestReimburseView,
    RequestReviewView,
    RequestSubmitDraftView,
    RequestSubmitIncreaseView,
    RequestSubmitView,
)
from reimbursements.views.receipt import (
    ReceiptCreateView,
    ReceiptDeleteView,
    ReceiptEditView,
    ReceiptFileView,
    ReceiptThumbnailView,
    RequestReceiptsView,
)
from reimbursements.views.request import (
    RequestCreateView,
    RequestCurrencyChangeView,
    RequestEditView,
    RequestPDFBundleView,
    RequestPayerChangeView,
    RequestView,
)
from reimbursements.views.transfer import (
    RequestTransferInitiateView,
    RequestTransferClaimView,
)

urlpatterns = [
    path("new", RequestCreateView.as_view(), name="request-new"),
    path("<int:pk>", RequestView.as_view(), name="request"),
    path("<int:pk>/pdf", RequestPDFBundleView.as_view(), name="request-pdf"),
    path("<int:pk>/edit", RequestEditView.as_view(), name="request-edit"),
    path(
        "<int:pk>/submit-draft",
        RequestSubmitDraftView.as_view(),
        name="request-submit-draft",
    ),
    path("<int:pk>/review", RequestReviewView.as_view(), name="request-review"),
    path(
        "<int:pk>/bank-details",
        BankFormSelectorView.as_view(),
        name="bank-form-selector",
    ),
    path(
        "<int:pk>/bank-details/<str:wise_type>",
        BankDetailsView.as_view(),
        name="bank-details",
    ),
    path("<int:pk>/submit", RequestSubmitView.as_view(), name="request-submit"),
    path("<int:pk>/delete", RequestDeleteView.as_view(), name="request-delete"),
    path(
        "<int:pk>/reimburse", RequestReimburseView.as_view(), name="request-reimburse"
    ),
    path(
        "<int:pk>/reimburse-return",
        RequestReimburseReturnView.as_view(),
        name="request-reimburse-return",
    ),
    path(
        "<int:pk>/request-increase",
        RequestSubmitIncreaseView.as_view(),
        name="request-submit-increase",
    ),
    path(
        "<int:pk>/request-comment",
        RequestCommentView.as_view(),
        name="request-comment",
    ),
    path(
        "<int:pk>/change-currency",
        RequestCurrencyChangeView.as_view(),
        name="request-change-currency",
    ),
    path(
        "<int:pk>/change-payer",
        RequestPayerChangeView.as_view(),
        name="request-change-payer",
    ),
    path("<int:pk>/receipts", RequestReceiptsView.as_view(), name="request-receipts"),
    path(
        "<int:request_id>/receipts/new", ReceiptCreateView.as_view(), name="add-receipt"
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/delete",
        ReceiptDeleteView.as_view(),
        name="delete-receipt",
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/edit",
        ReceiptEditView.as_view(),
        name="edit-receipt",
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/thumbnail",
        ReceiptThumbnailView.as_view(),
        name="view-receipt-thumbnail",
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/view-file",
        ReceiptFileView.as_view(),
        name="view-receipt-file",
    ),
    path(
        "<int:pk>/transfer",
        RequestTransferInitiateView.as_view(),
        name="request-transfer-initiate",
    ),
    path(
        "transfer/<str:token>",
        RequestTransferClaimView.as_view(),
        name="request-transfer-claim",
    ),
]

src/webui/urls.py
from django.urls import path

from webui.views import DeleteBankDetailsView, IndexView, ProfileEditView, ProfileView

urlpatterns = [
    path("", IndexView.as_view()),
    path("profile", ProfileView.as_view(), name="profile"),
    path("profile/edit", ProfileEditView.as_view(), name="profile-edit"),
    path(
        "profile/delete-bank-details",
        DeleteBankDetailsView.as_view(),
        name="profile-delete-bank-details",
    ),
]

src/reimbursements/models/profile.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Profile(models.Model):
    bank_details = models.JSONField(blank=True)
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"Profile for {self.user}"

src/reimbursements/models/receiptline.py
import datetime
from decimal import Decimal
from functools import lru_cache

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from historical_currencies.exceptions import ExchangeRateUnavailable
from historical_currencies.exchange import exchange

from reimbursements.models.receipt import Receipt
from reimbursements.models.request import Request
from reimbursements.models.types import ExpenseType


@lru_cache
def conversion_leeway_minimum(currency: str, date: datetime.date) -> Decimal:
    """Convert CONVERSION_LEEWAY_MINIMUM_USD to currency for date."""
    usd_minimum = Decimal(settings.CONVERSION_LEEWAY_MINIMUM_USD)
    return exchange(usd_minimum, "USD", currency, date)


class ReceiptLine(models.Model):
    receipt = models.ForeignKey(Receipt, on_delete=models.CASCADE, related_name="lines")
    date = models.DateField()
    description = models.TextField()
    amount = models.DecimalField(decimal_places=2, max_digits=15)
    currency = models.CharField(max_length=3)
    converted_amount = models.DecimalField(decimal_places=2, max_digits=15)
    expense_type = models.ForeignKey(ExpenseType, on_delete=models.PROTECT)

    @property
    def qualified_amount(self):
        return (self.amount, self.currency)

    @property
    def qualified_converted_amount(self):
        return (self.converted_amount, self.receipt.request.currency)

    @property
    def automatically_converted_amount(self):
        return exchange(
            self.amount, self.currency, self.receipt.request.currency, self.date
        )

    @property
    def qualified_automatically_converted_amount(self):
        return (self.automatically_converted_amount, self.receipt.request.currency)

    @property
    def conversion_within_limits(self):
        if not self.receipt.custom_conversion:
            return True
        request_currency = self.receipt.request.currency
        leeway_minimum = conversion_leeway_minimum(request_currency, self.date)
        auto_converted = self.automatically_converted_amount
        difference = self.converted_amount - auto_converted
        if difference < leeway_minimum:
            return True
        ratio = self.converted_amount / auto_converted
        leeway = Decimal(1 + settings.CONVERSION_LEEWAY_PERCENTAGE / 100)
        return ratio <= leeway

    def clean(self):
        super().clean()
        request = None
        currency_to = getattr(self, "initial_request_currency", None)
        try:
            request = self.receipt.request
            currency_to = request.currency
        except Receipt.DoesNotExist:
            pass
        except Request.DoesNotExist:
            pass
        if (
            self.amount
            and self.currency
            and currency_to
            and not self.receipt.custom_conversion
        ):
            try:
                self.converted_amount = exchange(
                    amount=self.amount,
                    currency_from=self.currency,
                    currency_to=currency_to,
                    date=self.date,
                )
            except ExchangeRateUnavailable:
                raise ValidationError(
                    {
                        "currency": _(
                            "No exchange rate available for %(currency_from)s "
                            "to %(currency_to)s for %(date)s. Please contact "
                            "an admin to get it imported."
                        )
                        % {
                            "currency_from": self.currency,
                            "currency_to": currency_to,
                            "date": self.date,
                        }
                    }
                )

        if (
            request
            and self.expense_type_id
            and not self.expense_type.request_types.filter(pk=request.request_type.pk)
        ):
            raise ValidationError(
                {
                    "expense_type": _("%s is not a valid expense type for %s requests")
                    % (self.expense_type.name, request.request_type.name),
                }
            )


@receiver(post_save, sender=Request)
def update_receipt_conversions(sender, instance, **kwargs):
    """Update converted_amounts. Backstop for things like edits in admin."""
    for receipt in instance.receipts.all():
        for line in receipt.lines.all():
            line.clean()
            line.save()

src/reimbursements/models/request.py
from datetime import timedelta
from decimal import Decimal

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.core.files import File
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils import crypto, timezone

from image_wrangler.client import PDFBundlerClient
from reimbursements.storage import generate_bundle_filename, receipts_storage

from reimbursements.models.history import RequestHistory
from reimbursements.models.reimbursement import ReimbursementLine
from reimbursements.models.types import RequestType, ExpenseTypeAllocation

User = get_user_model()


class Request(models.Model):
    class States(models.TextChoices):
        DRAFT = "draft", _("Draft")
        PENDING_APPROVAL = "pending_approval", _("Pending Approval")
        APPROVED = "approved", _("Approved")
        DELETED = "deleted", _("Deleted")
        PENDING_PAYMENT = "pending_payment", _("Pending Payment")
        PAID = "paid", _("Paid")

    requester = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=True)
    parent = models.ForeignKey(
        "Request",
        on_delete=models.PROTECT,
        null=True,
        related_name="children",
        blank=True,
    )
    state = models.CharField(
        max_length=16, choices=States.choices, default=States.DRAFT
    )
    bank_details = models.JSONField(null=True, blank=True)
    request_type = models.ForeignKey(RequestType, on_delete=models.PROTECT)
    description = models.TextField()
    expected_date = models.DateField(null=True, blank=True)
    currency = models.CharField(max_length=3, default=settings.DEFAULT_CURRENCY)
    approver_group = models.ForeignKey(
        Group, on_delete=models.PROTECT, null=True, related_name="requests_approver"
    )
    payer_group = models.ForeignKey(
        Group, on_delete=models.PROTECT, related_name="requests_payer"
    )
    visible = models.BooleanField(default=False)

    @property
    def subject(self):
        lines = self.description.splitlines()
        if lines:
            return lines[0].strip()
        return ""

    @property
    def total(self):
        return (
            self.lines.aggregate(total=models.Sum("amount"))["total"] or Decimal(0),
            self.currency,
        )

    @property
    def receipts_total(self):
        from reimbursements.models.receiptline import ReceiptLine

        lines = ReceiptLine.objects.filter(receipt__request=self)
        return (
            lines.aggregate(total=models.Sum("converted_amount"))["total"]
            or Decimal(0),
            self.currency,
        )

    @property
    def reimbursed_total(self):
        lines = ReimbursementLine.objects.filter(request=self)
        return (
            lines.aggregate(total=models.Sum("amount"))["total"] or Decimal(0),
            self.currency,
        )

    @property
    def created(self):
        try:
            return self.history.get(event=RequestHistory.Events.CREATED).timestamp
        except RequestHistory.DoesNotExist:
            return None

    @property
    def updated(self):
        last_event = self.history.all().last()
        if last_event:
            return last_event.timestamp
        return None

    def get_absolute_url(self):
        return reverse("request", kwargs={"pk": self.pk})

    def get_fully_qualified_url(self):
        return settings.SITE_URL.rstrip("/") + self.get_absolute_url()

    def summarize_by_type(self):
        summary = {}
        total = ExpenseTypeAllocation("Total", self.currency, special=True)
        for line in self.lines.all():
            if line.expense_type_id not in summary:
                summary[line.expense_type_id] = ExpenseTypeAllocation(
                    line.expense_type.name, self.currency
                )
            summary[line.expense_type_id].requested += line.amount
            total.requested += line.amount
        for line in self.reimbursement_lines.all():
            if line.expense_type_id not in summary:
                summary[line.expense_type_id] = ExpenseTypeAllocation(
                    line.expense_type.name, self.currency
                )
            summary[line.expense_type_id].reimbursed += line.amount
            total.reimbursed += line.amount
        for receipt in self.receipts.all():
            for line in receipt.lines.all():
                if line.expense_type_id not in summary:
                    summary[line.expense_type_id] = ExpenseTypeAllocation(
                        line.expense_type.name, self.currency
                    )
                summary[line.expense_type_id].spent += line.converted_amount
                total.spent += line.converted_amount
        summary["total"] = total
        return summary

    def summarize_by_type_dict(self):
        allocation = {}
        for k, v in self.summarize_by_type().items():
            allocation[v.name] = v.to_dict()
        return allocation

    @property
    def approved_budget_limit(self):
        """The total requested, plus acceptable leeway"""
        total = self.total[0]
        approved_limit = total * (
            1 + Decimal(settings.OVERBUDGET_LEEWAY_PERCENTAGE) / 100
        )
        return (approved_limit, self.currency)

    @property
    def total_reimburseable(self):
        """The total requested, cut off at approved_budget_limit"""
        approved_total = min(self.approved_budget_limit[0], self.receipts_total[0])
        return (approved_total, self.currency)

    @property
    def within_budget(self):
        budget = self.approved_budget_limit[0]
        receipts_total = self.receipts_total[0]
        return receipts_total <= budget

    @property
    def over_budget(self):
        return not self.within_budget

    def __str__(self):
        return f"Request {self.id}: {self.subject}"

    def user_access(self, user, access_key=False):
        """What access levels does user have to this Request"""
        access = {}
        if self.requester == user and self.requester is not None:
            access["requester"] = True
        if user.is_superuser:
            access["admin"] = True
        if self.visible:
            if user.groups.filter(id=self.approver_group_id).exists():
                access["approver"] = True
            if user.groups.filter(id=self.payer_group_id).exists():
                access["payer"] = True
        if access_key:
            access["access_key"] = True
        return access

    @property
    def requester_name(self) -> str | None:
        """Helper for templates, to render the requester's name"""
        if not self.requester:
            return "Currently Unclaimed"
        name = self.requester.get_full_name()
        if not name:
            name = self.requester.username
        return name

    def generate_pdf_bundle(self):
        """Create a PDF bundle of the request"""
        content = [
            {"url": self.get_fully_qualified_url()},
        ]
        files = []
        for receipt in self.receipts.all():
            content.append({"filename": receipt.file.name})
            files.append(receipt.file)
        manifest = {"content": content}
        PDFBundlerClient(manifest, self, files).bundle_pdf()

    @property
    def pdf_bundle(self) -> File:
        """Open the PDF bundle file and return it."""
        return receipts_storage.open(generate_bundle_filename(self))

    def delete_pdf_bundle(self):
        """Delete any existing PDF bundle."""
        return receipts_storage.delete(generate_bundle_filename(self))

    def initiate_transfer(self, expire_days=60):
        from reimbursements.models.transfer import RequestTransfer

        transfer = RequestTransfer(
            request=self,
            expires=timezone.now() + timedelta(days=expire_days),
            token=crypto.get_random_string(length=20),
        )
        transfer.save()
        return transfer

    @property
    def pretty_bank_details(self) -> dict[str, str] | None:
        from reimbursements.forms.bank_details import label_bank_details

        if self.bank_details:
            return label_bank_details(self.bank_details)
        return None

src/reimbursements/templates/reimbursements/bank_details.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
{% trans "Add Bank Details" %}
{% endblock %}
{% block content %}
<h1>{% trans "Add Bank Details" %}</h1>
<p>
  {% url "bank-form-selector" object.pk as selector_url %}
  {% blocktrans %}
    Please enter the appropriate details for your bank.
    If this is not the appropriate kind of transfer for your bank, please
    <a href="{{ selector_url }}">select</a> another form.
  {% endblocktrans %}
</p>
<h2>{{ form.description }}</h2>
<form method="post">
  {% crispy form %}
  <input type="submit" class="btn btn-primary" value="{% trans 'Save' %}">
</form>
{% endblock %}

src/reimbursements/templates/reimbursements/bank_form_selector.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
{% trans "Select Bank Transfer Type" %}
{% endblock %}
{% block content %}
<h1>{% trans "Select Bank Transfer Type" %}</h1>
<p>{% trans "Please select an appropriate transfer method for your bank." %}</p>
{% if selected %}
  <h2>{% trans "Previously Selected:" %}</h2>
  <div>
    <a class="btn btn-primary"
       href="{% url "bank-details" pk=object.pk wise_type=selected.wise_type %}"
    >{{ selected.description }}</a>
  </div>
{% endif %}
{% if saved %}
  <h2>{% trans "Previously Saved:" %}</h2>
  <div>
    <a class="btn btn-primary"
       href="{% url "bank-details" pk=object.pk wise_type=saved.wise_type %}"
    >{{ saved.description }}</a>
  </div>
{% endif %}
{% if recommended %}
  <h2>
    {% blocktrans with currency=object.currency %}
      Recommended for {{currency}}:
    {% endblocktrans %}
  </h2>
  <div>
    <a class="btn btn-primary"
       href="{% url "bank-details" pk=object.pk wise_type=recommended.wise_type %}"
    >{{ recommended.description }}</a>
  </div>
{% endif %}
<h2>{% trans "Default:" %}</h2>
<div>
  <a class="btn btn-success"
     href="{% url "bank-details" pk=object.pk wise_type=default.wise_type %}"
  >{{ default.description }}</a>
</div>
{% endblock %}

src/reimbursements/templates/reimbursements/edit_request.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
  {% if object.pk %}
    {% trans "Edit Request" %}
  {% else %}
    {% trans "New Request" %}
  {% endif %}
{% endblock %}
{% block content %}
<h1>
  {% if object.pk %}
    {% trans "Edit Request" %}
  {% else %}
    {% trans "New Request" %}
  {% endif %}
</h1>
<p>
  {% blocktrans %}
    This is a request for budget pre-approval to make an expense for the
    project.
    You don't need to break it down into every expected item, just into broad
    categories, for review of your request.
    Once approved, you may make the expenses and will get an opportunity to
    upload receipts.
  {% endblocktrans %}
</p>
<form method="post">
  {% crispy form %}
  {# https://github.com/django-crispy-forms/crispy-bootstrap5/issues/174 #}
  {% include "bootstrap5/errors_formset.html" %}
  {% crispy formset formset_helper %}
  <div class="fs-4 pb-3">
    {% trans "Total:" %}
    <span id="total">{% trans "Calculated by Javascript..." %}</span>
  </div>
  <a class="btn btn-secondary" id="add_line">{% trans "Add Item" %}</a>
  <input type="submit" class="btn btn-primary" value="{% trans 'Save Draft' %}">
</form>
{% endblock %}
{% block extra_foot %}
{{ expense_type_map|json_script:"expense_type_map"}}
<script>
  "use strict";
  (function() {
    const update_total = function(event) {
      var total = 0;
      document.querySelectorAll("form tbody tr:not(.empty-form)").forEach(row => {
        const deleted = row.querySelector("input[id$=-DELETE").checked;
        const amount = parseFloat(row.querySelector("input[id$=-amount]").value) || 0;
        if (!deleted) {
          total += amount;
        }
      });
      const currency = document.querySelector("select#id_currency").value;
      const rendered = new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: currency,
      }).format(total);
      document.querySelector("span#total").textContent = rendered;
    }

    document.querySelector("select#id_currency").addEventListener("input", update_total);
    const update_total_listener_selector = "input[id$=-amount], input[id$=-DELETE]";
    document.querySelectorAll(update_total_listener_selector).forEach(el => {
      el.addEventListener("input", update_total);
    });
    update_total();

    const add_button = document.querySelector("#add_line");
    add_button.addEventListener("click", (event) => {
      const total_forms_input = document.querySelector("#id_lines-TOTAL_FORMS");
      const index = parseInt(total_forms_input.getAttribute("value"));
      const empty_form = document.querySelector(".empty-form");
      const new_form = empty_form.innerHTML.replace(/__prefix__/g, index);
      empty_form.parentElement.insertAdjacentHTML("beforeend", new_form);
      const new_row = empty_form.parentElement.lastElementChild;
      total_forms_input.setAttribute("value", index + 1);
      new_row.querySelectorAll(update_total_listener_selector).forEach(el => {
        el.addEventListener("input", update_total);
      });
    });

    const expense_type_map = JSON.parse(
      document.getElementById("expense_type_map").textContent);
    const request_type_select = document.querySelector("select#id_request_type");
    const update_expense_types = function(event) {
      const request_type = parseInt(request_type_select.value);
      const valid_expense_types = expense_type_map[request_type] || [];
      document.querySelectorAll("select[id$=-expense_type]").forEach(el => {
        el.querySelectorAll("option").forEach(opt => {
          if (opt.value) {
            opt.disabled = !valid_expense_types.includes(parseInt(opt.value));
          }
        });
      });
    };
    request_type_select.addEventListener("input", update_expense_types);
    update_expense_types();
  })();
</script>
{% endblock %}

src/reimbursements/templates/reimbursements/request_receipts.html
{% extends 'base.html' %}
{% load i18n %}
{% load currency_format %}
{% block page_title %}
{% blocktrans with id=object.id subject=object.subject %}
  Receipts for request {{ id }}: {{ subject }}
{% endblocktrans %}
{% endblock %}
{% block extra_head %}
<style type="text/css">
.table .xe {
  background-color: #0000ff10;
}
</style>
{% endblock %}
{% block content %}
<h1>
  {% blocktrans with id=object.id subject=object.subject %}
    Receipts for request {{ id }}: {{ subject }}
  {% endblocktrans %}
</h1>
{% for receipt in object.receipts.all %}
  <h2>{{ receipt.subject }}</h2>
  <p>
    <a class="btn btn-warning float-end"
       href="{% url "edit-receipt" object.id receipt.id %}">{% trans "Edit Receipt" %}</a>
    {{ receipt.description|linebreaksbr }}
  </p>
  {% if receipt.file.path.lower|slice:"-4:" == ".pdf" %}
    <object data="{% url "view-receipt-file" object.id receipt.id %}"
            type="application/pdf" width="1296" height="1296">
      <div>
        {% trans "Unfortunately your browser can't display inline PDFs." %}
        <a class="btn btn-info"
            href="{% url "view-receipt-file" object.id receipt.id %}">
          {% trans "Download" %}
        </a>
      </div>
    </object>
  {% else %}
    <img src="{% url "view-receipt-file" object.id receipt.id %}"
         class="img-fluid receipt">
  {% endif %}
  {% if receipt.lines.exists %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>{% trans "Date" %}</th>
          <th>{% trans "Description" %}</th>
          <th>{% trans "Expense Type" %}</th>
          <th class="text-end">{% trans "Amount" %}</th>
          <th class="text-end"
              title="{% trans "Calculated based on the exchange rate of the receipt date" %}">
            {% blocktrans with currency=object.currency %}
              Amount {{ currency }}
            {% endblocktrans %}
          </th>
          {% if object.currency != "USD" %}
            <th class="text-end xe"
                title="{% trans "Calculated based on current exchange rates" %}">
              {% trans "Amount USD" %}
            </th>
          {% endif %}
          {% if object.currency != "EUR" %}
            <th class="text-end xe"
                title="{% trans "Calculated based on current exchange rates" %}">
              {% trans "Amount EUR" %}
            </th>
          {% endif %}
        </tr>
      </thead>
      {% for line in receipt.lines.all %}
        <tr>
          <td>{{ line.date }}</td>
          <td>{{ line.description|linebreaksbr }}</td>
          <td>{{ line.expense_type }}</td>
          <td class="text-end">{{ line.qualified_amount|currency }}</td>
          <td class="text-end">{{ line.qualified_converted_amount|currency }}</td>
          {% if object.currency != "USD" %}
            <td class="text-end xe">{{ line.qualified_converted_amount|exchange:"USD" }}</td>
          {% endif %}
          {% if object.currency != "EUR" %}
            <td class="text-end xe">{{ line.qualified_converted_amount|exchange:"EUR" }}</td>
          {% endif %}
        </tr>
      {% endfor %}
      <tr>
        <th colspan="4">{% trans "Receipt Subtotal" %}</th>
        <td class="text-end">{{ receipt.total|currency }}</td>
        {% if object.currency != "USD" %}
          <td class="text-end xe">{{ receipt.total|exchange:"USD" }}</td>
        {% endif %}
        {% if object.currency != "EUR" %}
          <td class="text-end xe">{{ receipt.total|exchange:"EUR" }}</td>
        {% endif %}
      </tr>
    </table>
  {% endif %}
{% endfor %}
{% endblock %}

src/reimbursements/templates/reimbursements/transfer_claim.html
{% extends "base.html" %}
{% load i18n %}
{% load currency_format %}
{% block page_title %}
{% trans "Claim Request" %}
{% endblock %}
{% block content %}
<h1>{% trans "Claim Request" %}</h1>
<p>
  {% blocktrans with subject=object.subject %}
    You can take ownership of an existing request for {{ subject }}.
  {% endblocktrans %}
</p>
<table class="table table-striped">
  <tr>
    <th>{% trans "Requester" %}</th>
    <td>{{ object.requester_name }}</td>
  </tr>
  <tr>
    <th>{% trans "State" %}</th>
    <td>{{ object.get_state_display }}</td>
  </tr>
  <tr>
    <th>{% trans "Request Type" %}</th>
    <td>{{ object.request_type }}</td>
  </tr>
  <tr>
    <th>{% trans "Description" %}</th>
    <td>{{ object.description|linebreaksbr }}</td>
  </tr>
  <tr>
    <th>{% trans "Currency" %}</th>
    <td>
      {{ object.currency }}
      <i class="bi bi-question-square" data-bs-toggle="tooltip" title="{% trans "If this is not your preferred currency for reimbursal, you can change the currency, once you've claimed the request." %}"></i>
    </td>
  </tr>
  <tr>
    <th>{% trans "Payers" %}</th>
    <td>
      {{ object.payer_group.name }}
      <i class="bi bi-question-square" data-bs-toggle="tooltip" title="{% trans "If this is not the best option to reimburse you, contact them or the approver, once you've claimed the request." %}"></i>
    </td>
  </tr>
  <tr>
    <th>{% trans "Total" %}</th>
    <td class="text-end">
      {{ object.total|currency }}
    </td>
  </tr>
  <tr>
    <th>{% trans "Converted Total" %}</th>
    <td class="text-end">
      {% if object.currency != "USD" %}
        {{ object.total|exchange:"USD" }}
      {% endif %}
      {% if object.currency != "USD" and object.currency != "EUR" %}
        <br>
      {% endif %}
      {% if object.currency != "EUR" %}
        {{ object.total|exchange:"EUR" }}
      {% endif %}
    </td>
  </tr>
</table>
<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-primary" value="{% trans 'Claim' %}">
</form>
{% endblock %}
{% block extra_foot %}
<script>
  "use strict";
  (function() {
    const tooltipTriggerList = [].slice.call(
      document.querySelectorAll('[data-bs-toggle="tooltip"]'));
    const tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl)
    })
  })();
</script>
{% endblock %}